version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: project-ms-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project-ms
