services:

  postgres:
    image: postgres:16
    container_name: projects-ms-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: projects-ms
